apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::845601657294:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1YMHHQN6ZTWS
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
        - system:masters
      rolearn: arn:aws:iam::845601657294:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-08T14:13:18Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1268"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 0e211244-ce66-4dc8-bd67-1872b0f2b2aa
